---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dex-helm
  namespace: security-system
spec:
  interval: 1h
  path: ./kubernetes/home-k8s/apps/security-system/dex/helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
