---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics-k8s-stack-helm
  namespace: observability-system
spec:
  dependsOn:
    - name: piraeus-operator-app
      namespace: storage-system
  interval: 1h
  path: ./kubernetes/home-k8s/apps/observability-system/victoria-metrics-k8s-stack/helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
