---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator-helm
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/home-k8s/apps/flux-system/flux-operator/helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator-app
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/home-k8s/apps/flux-system/flux-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m
  wait: true
