---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync-helm
  namespace: storage-system
spec:
  dependsOn:
    - name: piraeus-operator-app
      namespace: storage-system
    - name: snapshot-controller-helm
      namespace: storage-system
  interval: 1h
  path: ./kubernetes/home-k8s/apps/storage-system/volsync/helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m
  wait: true
