---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tofu-controller-helm
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/home-k8s/apps/flux-system/tofu-controller/helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m
  wait: true
