---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: piraeus-operator
  namespace: storage
spec:
  chartRef:
    kind: OCIRepository
    name: piraeus-operator
  interval: 1h
  values:
    installCRDs: true
    leaderElect: true
    replicaCount: 3
