---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: piraeus-datastore

resources:
  - ./namespace.yaml
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./linstor-tls.yaml
  - ./linstor-cluster.yaml
  - ./linstor-satellite-configuration.yaml
  - ./storage-class.yaml
