---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-replica-1
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  linstor.csi.linbit.com/storagePool: zfs-flash-pool
  linstor.csi.linbit.com/placementCount: "1"
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "false"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-replica-3
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  linstor.csi.linbit.com/storagePool: zfs-flash-pool
  linstor.csi.linbit.com/placementCount: "3"
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "false"
