---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: replica-1-flash
allowVolumeExpansion: true
parameters:
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "false"
  linstor.csi.linbit.com/placementCount: "1"
  linstor.csi.linbit.com/storagePool: vg1-thin
provisioner: linstor.csi.linbit.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: replica-3-flash
allowVolumeExpansion: true
parameters:
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "false"
  linstor.csi.linbit.com/placementCount: "3"
  linstor.csi.linbit.com/storagePool: vg1-thin
provisioner: linstor.csi.linbit.com
volumeBindingMode: WaitForFirstConsumer
