---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluentbit
  namespace: fluentbit
spec:
  interval: 1h
  path: ./kubernetes/fluentbit
  prune: true
  retryInterval: 2m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m
