---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-system
resources:
  - ./namespace.yaml
  - ./fluent-bit/ks.yaml
  - ./grafana-operator/ks.yaml
  - ./victoria-metrics-k8s-stack/ks.yaml
