---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network-system
resources:
  - ./namespace.yaml
  - ./cert-manager/ks.yaml
  - ./envoy-gateway/ks.yaml
