---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: spegel
  namespace: spegel
spec:
  interval: 1h
  path: ./kubernetes/spegel/app
  prune: true
  retryInterval: 2m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m
