---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mtls-ca
  namespace: network-system
spec:
  commonName: mtls-ca
  secretName: mtls-ca
  duration: 87600h # 10 years
  isCA: true
  usages:
    - signing
    - key encipherment
    - cert sign
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
