---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: network-system
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager
  interval: 1h
  values:
    cainjector:
      replicaCount: 3
    crds:
      enabled: true
    replicaCount: 3
    webhook:
      networkPolicy:
        enabled: false
      replicaCount: 3
