---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: piraeus-operator
  namespace: storage
spec:
  interval: 1h
  path: ./kubernetes/apps/storage/piraeus-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
