---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluentbit
  namespace: observability
spec:
  interval: 1h
  path: ./kubernetes/observability/fluentbit
  prune: true
  retryInterval: 2m
  wait: true
  dependsOn:
    - name: spegel
      namespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m