---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
  namespace: piraeus-datastore
spec:
  interval: 1h
  path: ./kubernetes/piraeus-datastore/app
  prune: true
  retryInterval: 2m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m
