---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: piraeus-operator
  namespace: storage-system
spec:
  interval: 1h
  path: ./kubernetes/home-k8s/apps/storage-system/piraeus-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
