---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: piraeus-operator-helm
  namespace: storage-system
spec:
  interval: 1h
  path: ./kubernetes/home-k8s/apps/storage-system/piraeus-operator/helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: piraeus-operator-app
  namespace: storage-system
spec:
  dependsOn:
    - name: piraeus-operator-helm
      namespace: storage-system
    - name: cert-manager-helm
      namespace: network-system
  interval: 1h
  path: ./kubernetes/home-k8s/apps/storage-system/piraeus-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
