---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluent-bit
  namespace: observability-system
spec:
  interval: 1h
  path: ./kubernetes/home-k8s/apps/observability-system/fluent-bit/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
