---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
  namespace: security-system
spec:
  interval: 15m
  ref:
    tag: 0.0.52
  url: oci://ghcr.io/home-operations/charts/tuppr
